part of "element_property_view.dart";

typedef BuildFn = Widget Function(ElementPropertyView);

const _buildFnLookup = <ElementType, BuildFn>{
  ElementType.text: _buildText,
  ElementType.image: _buildImage,
  ElementType.textField: _buildTextField,
  ElementType.slider: _buildSlider,
  ElementType.switch_: _buildSwitch,
  ElementType.richText: _buildRichText,
  ElementType.checkbox: _buildCheckbox,
  ElementType.radio: _buildRadio,
  // Single-child elements
  ElementType.elevatedButton: _buildElevatedButton,
  ElementType.animatedBuilder: _buildAnimatedBuilder,
  ElementType.absorbPointer: _buildAbsorbPointer,
  ElementType.offstage: _buildOffstage,
  ElementType.decoratedBox: _buildDecoratedBox,
  ElementType.center: _buildCenter,
  ElementType.positioned: _buildPositioned,
  ElementType.align: _buildAlign,
  ElementType.transform: _buildTransform,
  ElementType.appBar: _buildAppBar,
  ElementType.inkWell: _buildInkWell,
  ElementType.subtree: _buildSubtree,
  ElementType.meta: _buildMeta,
  ElementType.repaintBoundary: _buildRepaintBoundary,
  ElementType.overflowBox: _buildOverflowBox,
  ElementType.animatedSize: _buildAnimatedSize,
  ElementType.intrinsicHeight: _buildIntrinsicHeight,
  ElementType.intrinsicWidth: _buildIntrinsicWidth,
  ElementType.rotatedBox: _buildRotatedBox,
  ElementType.constrainedBox: _buildConstrainedBox,
  ElementType.backdropFilter: _buildBackdropFilter,
  ElementType.animatedOpacity: _buildAnimatedOpacity,
  ElementType.remoteSubtree: _buildRemoteSubtree,
  ElementType.safeArea: _buildSafeArea,
  ElementType.card: _buildCard,
  ElementType.animatedContainer: _buildAnimatedContainer,
  ElementType.animatedAlign: _buildAnimatedAlign,
  ElementType.animatedRotation: _buildAnimatedRotation,
  ElementType.animatedPadding: _buildAnimatedPadding,
  ElementType.animatedPositioned: _buildAnimatedPositioned,
  ElementType.animatedScale: _buildAnimatedScale,
  ElementType.expanded: _buildExpanded,
  ElementType.sizedBox: _buildSizedBox,
  ElementType.container: _buildContainer,
  ElementType.gestureDetector: _buildGestureDetector,
  ElementType.coloredBox: _buildColoredBox,
  ElementType.padding: _buildPadding,
  ElementType.lifecycleStateListener: _buildLifecycleStateListener,
  ElementType.singleChildScrollview: _buildSingleChildScrollView,
  ElementType.radioGroupContext: _buildRadioGroupContext,
  ElementType.ignorePointer: _buildIgnorePointer,
  ElementType.opacity: _buildOpacity,
  ElementType.fittedBox: _buildFittedBox,
  ElementType.sliverPadding: _buildSliverPadding,
  ElementType.customScrollView: _buildCustomScrollView,
  ElementType.sliverFillRemaining: _buildSliverFillRemaining,
  ElementType.sliverToBoxAdapter: _buildSliverToBoxAdapter,
  ElementType.sliverFillViewport: _buildSliverFillViewport,
  ElementType.sliverOpacity: _buildSliverOpacity,
  ElementType.sliverAnimatedOpacity: _buildSliverAnimatedOpacity,
  ElementType.sliverOffstage: _buildSliverOffstage,
  ElementType.sliverIgnorePointer: _buildSliverIgnorePointer,
  ElementType.sliverSafeArea: _buildSliverSafeArea,
  ElementType.animatedCrossFade: _buildAnimatedCrossFade,
  ElementType.physicalModel: _buildPhysicalModel,
  ElementType.animatedPhysicalModel: _buildAnimatedPhysicalModel,
  ElementType.animatedSlide: _buildAnimatedSlide,
  ElementType.animatedPositionedDirectional:
      _buildAnimatedPositionedDirectional,
  ElementType.clipRect: _buildClipRect,
  ElementType.clipOval: _buildClipOval,
  ElementType.aspectRatio: _buildAspectRatio,
  ElementType.baseline: _buildBaseline,
  ElementType.limitedBox: _buildLimitedBox,
  ElementType.fractionallySizedBox: _buildFractionallySizedBox,
  ElementType.sizedOverflowBox: _buildSizedOverflowBox,
  ElementType.fractionalTranslation: _buildFractionalTranslation,
  ElementType.unconstrainedBox: _buildUnconstrainedBox,
  ElementType.semantics: _buildSemantics,
  ElementType.mergeSemantics: _buildMergeSemantics,
  ElementType.excludeSemantics: _buildExcludeSemantics,
  // Multi-child elements
  ElementType.column: _buildColumn,
  ElementType.row: _buildRow,
  ElementType.stack: _buildStack,
  ElementType.component: _buildComponent,
  ElementType.listView: _buildListView,
  ElementType.gridView: _buildGridView,
  ElementType.carouselView: _buildCarouselView,
  ElementType.sliverList: _buildSliverList,
  ElementType.sliverGrid: _buildSliverGrid,
  ElementType.wrap: _buildWrap,
  ElementType.scaffold: _buildScaffold,
  ElementType.sliverVisibility: _buildSliverVisibility,
  ElementType.sliverAppBar: _buildSliverAppBar,
  ElementType.flexibleSpaceBar: _buildFlexibleSpaceBar,
  ElementType.pageView: _buildPageView,
  ElementType.badge: _buildBadge,
};
