name: PR auto-review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
