name: Publish plugin

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.PUB_CRED }}
          flutter_package: true
          skip_test: false
          dry_run: true
