name: Publish package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-pubdev-credentials@v1
      # Setup Flutter SDK
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
      - name: Install dependencies
        run: flutter pub get
      # Here you can insert custom steps you need
      - name: Publish
        run: flutter pub publish --force
