name: Publish flutter_duit

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - run: flutter pub get
      - run: flutter pub publish --force 
    permissions:
      id-token: write # Required for authentication using OIDC
