name: Pre-Publish

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart fix --dry-run
      - run: flutter pub publish --dry-run
    permissions:
      id-token: write
