name: Run tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, closed]

env:
  IS_CI: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
    permissions:
      id-token: write